import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchCount } from '@helpers/balanceAPI';

const initialState = {
  value: 5000,
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const incrementAsync = createAsyncThunk(
  'balance/fetchCount',
  async (amount) => {
    const response = await fetchCount(amount);
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const balanceSlice = createSlice({
  name: 'balance',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    addToBalance:  (state, action) => {
      state.value += action.payload;
    },
    withdrawBalance:  (state, action) => {
      state.value -= action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(incrementAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(incrementAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.value += action.payload;
      });
  },
});

export const { addToBalance, withdrawBalance } = balanceSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectBalance = (state) => state.balance.value;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
export const incrementIfOdd = (amount) => (dispatch, getState) => {
  const currentValue = selectBalance(getState());
  if (currentValue % 2 === 1) {
    dispatch(addToBalance(amount));
  }
};

export default balanceSlice.reducer;
